version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.1-apache
#    build:
#      context: .
#      dockerfile: DockerfilePHP
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    depends_on:
      - mysql

  composer_installation:
    container_name: composer_installation
    image: composer
    volumes:
      - ./:/app:delegated
    command: composer install

  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: user_test
      MYSQL_PASSWORD: password_test
    ports:
      - '3307:3306'